[package]
name = "komodo_airdrop"
description = "An airdrop manager for Komodo and its assetchains"
version = "0.0.1"
authors = ["Jorian <jorian@outlook.com>"]
edition = "2018"
license = "MIT"

[dependencies]
